export const GET_POKEMONS = "GET_POKEMONS"
export const ORDER_POKE_AZ_ZA = "ORDER_POKE_AZ_ZA"
export const ORDER_ATTACK = "ORDER_ATTACK"
export const SET_IMAGE = "SET_IMAGE"
export const SET_INPUT = "SET_INPUT"
export const SET_ID = "SET_ID"
export const GET_TYPE = "GET_TYPE"
export const ORDER_TYPE = "ORDER_TYPE"
export const REFRESH = "REFRESH"

// export const CARRUSEL = "CARRUSEL"